name: CI

on:
  push:
    branches:
      - dev
      - master

env:
  PYTHON_VERSION: 3.9

jobs:
  multi_arch_build:
    runs-on: ubuntu-latest
    name: Image Build
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build web
        run: make build_web
      - name: Build image
        run: make push